version: "3.8"

networks:
  botu_net:
    external: true

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://botu:${DB_PASS}@postgres:5432/botu
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - botu_net
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.botut.net`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.services.api.loadbalancer.server.port=8000

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - botu_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`botut.net`,`www.botut.net`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls.certresolver=letsencrypt
      - traefik.http.services.web.loadbalancer.server.port=80

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=botu
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=botu
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - botu_net

volumes:
  pg_data:
    external: true
